#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math
from dnslib import DNSRecord, DNSHeader, RR, QTYPE, A, RCODE

class Server:
    def __init__(self, root_ip, zone, port):
        self.root_ip = root_ip

        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(("0.0.0.0", port))
        self.port = self.socket.getsockname()[1]

        self.log("Bound to port %d" % self.port)

        with open(zone, "r") as f:
            zone_data = f.read()
        
        self.records = RR.fromZone(zone_data)
        self.log("Auth zone records:")
        for record in self.records:
            self.log(str(record))
            if QTYPE[record.rtype] == "SOA":
                self.domain = record.rname
        self.log("Domain name: %s" % self.domain)


    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, addr, message):
        self.log("Sending message:\n%s" % message)
        self.socket.sendto(message.pack(), addr)
    
    def compare_types(self, type1, type2):
        if type1 in [QTYPE.A, QTYPE.CNAME]:
            return type2 in [QTYPE.A, QTYPE.CNAME]
        else:
            return type1 == type2

    def find_records(self, qname, qtype = None, glues = None):
        matches = []
        for record in self.records:
            if record.rname == qname:
                if qtype and not self.compare_types(qtype, record.rtype):
                    continue
                matches.append(record)
                if record.rtype == QTYPE.CNAME:
                    matches.extend(self.find_records(record.rdata.label))
                if record.rtype == QTYPE.NS and glues != None:
                    glues.extend(self.find_records(record.rdata.label))
                
        return matches

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Unpack the DNS request
        request = DNSRecord.parse(data)
        self.log("Received message:\n%s" % request)

        response = request.reply()
        for q in request.questions:
            if q.qname.matchSuffix(self.domain):
                glues = []
                matches = self.find_records(q.qname, q.qtype, glues)
                if not matches:
                    response.header.rcode = RCODE.NXDOMAIN
                for record in matches:
                    response.add_answer(record)
                for record in glues:
                    response.add_ar(record)

        
        self.send(addr, response)

    def run(self):
        seq = 0
        while True:
            socks = select.select([self.socket], [], [], 0.1)[0]
            for conn in socks:
                self.recv(conn)

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('root_ip', type=str, help="The IP address of the root server")
    parser.add_argument('zone', type=str, help="The zone file for this server")
    parser.add_argument('--port', type=int, help="The port this server should bind to", default=0)
    args = parser.parse_args()
    sender = Server(args.root_ip, args.zone, args.port)
    sender.run()
